language: ruby
dist: trusty
group: edge
rvm:
- 2.4.0
deploy:
  provider: heroku
  app: cob-search
  on: master
  api_key:
    secure: RVVIFqf/988xJSjAK8immISVuN1oXmf8K4S2+D0igvKYe9UXNHMGBCJLagq0/3q93b9t9tasDBnGj6Mut87hPKq7apUm0cnEZiEnrc2kiQ6X2BrSb+KqjmVH75OCpo3L9B9nYfDYpMJ4eNQLBI3X4jxptwCeSI7TvzSbJ2DgTSFhiNAeiMj5EiT190Ef7olLcLiJC+Yl8ifs7nxSWIyGFAdNjc/gx1QkhCEzhHZd7lPX6fwCwK0HzJAvQYcHezoK8HfN9ZYkoJSlnn7i3TsIOLg7Ylln0qieb4X4HVJguOosxdIj6hh/HB0WkWIGXntZyCzjcGk+IlZ8SnxbBo/mXBYYOD7/FsoGA/FqIqIaKcn39hFGHCl5+9qGHKKY/sGQWHUJzCPhm2XZCQhCDHErl7h9wsjvNQCgJQevQ995TelpHQ216+TT59D+ywtvuf+EqC6ytrw2PilQyKhUbgr/8o4XdjPqCVYe0Ni0E5zcGTCq5cgHy1boLfXAf6qcZQvNHKwhN5Ig4J5A0D2IJUAdexwhA0G+x2hnm+nEDXdasYg88fsT1ItIfjMi5Ojj8jr4xATa9HU0ych+QO9cjOWZw64xToccT78NESUOlM/9FnOGSn5Evagh6HXqq5ev4hyxTeEytegP6a6ueYz8kOSIysYO1E+tnQ4WXXTB9Y/EEHA=
notifications:
  slack:
    secure: b2UX5FnE2/C5MDNK47EP0GZIRmfwX+18HES0Q/uSwt6t7+ogKCtIjWCp1sIPd7jqRak0VmLoM0OHy6MBjz6x+1MQMNUqPEiO1f2APgBJ48c6rzeWQKTVfrKsUvPYIA+gxQ7jq7Gn0zPYQ5/+KXkxac+NrVoH85sI0xIL2BhFgQu1W4OlLLFKT11U7zJtCi3bcYhF7/eyCcrs3+IBGGp9sldjWvaVLDqUnFjz3c5AXwxlbJ6UTq7GIdIEe5Xw/UOJS9weedhoYH2XSNzFpmqqkAGcvkFpgCeYxf12iiqkmoAq5A0CxWVXqA3vG+imabuQonpbQsGdvtFP71EV9o9DxwATwxaGhBpX+Sw4zN7v25IC6n7rcvcK2F9dtY0CAb8BpWbEbWMDXXmVvFEVAvgARQ/b+L7YOJbNbbJwJQqZkllJp0lAFluyMDwpP2Ncr177S5hR/4Z6rlj1aLK1nhbmi/tK/kSNe+bcashm7/S2KG076hN0b5TB87hsbkvHsnVJDMKXSHwKrrdJiXDAkwZbl2sBp/bbfMTXyEqrINUG4WA70WXP3lR/QJy2pldVEYIU5rRwSzZ0BJ9raF7iiXFgTn3+Yhl0U/UgcDCEKoRvutM/suCy1mQBYP+Gv1uyFNFco37doQbPeyAXNb1vjfJQtyzy8I31gIN/sK590YxLBCA=
